#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using TES.Common.Enumerations;
    using TES.Common.Extensions;
    using TES.Merchant.Web.UI;
    using TES.Merchant.Web.UI.ViewModels;
    using TES.Security;
    using TES.Web.Core;
    using TES.Web.Core.Extensions;
    using TES.Web.Core.Helper;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class _Views_Account_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "تغییر رمز عبور";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Account\ChangePassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Account\ChangePassword.cshtml"
     if (ViewBag.PasswordExpired != null && ViewBag.PasswordExpired)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n            <p>رمز عبور شما منقضی شده است. لطفاً نسبت به تغییر آن اقدام نمایید" +
".</p>\r\n        </div>\r\n");

            
            #line 11 "..\..\Views\Account\ChangePassword.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h1");

WriteLiteral(" class=\"header-title\"");

WriteLiteral(">تغییر رمز عبور</h1>\r\n</div>\r\n\r\n<form");

WriteAttribute("action", Tuple.Create(" action=\"", 369), Tuple.Create("\"", 418)
            
            #line 16 "..\..\Views\Account\ChangePassword.cshtml"
, Tuple.Create(Tuple.Create("", 378), Tuple.Create<System.Object, System.Int32>(Url.Action("ChangePassword", "Account")
            
            #line default
            #line hidden
, 378), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"AccountChangePasswordForm\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Account\ChangePassword.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(" for=\"CurrentPassword\"");

WriteLiteral(">رمز عبور فعلی</label>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"CurrentPassword\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"CurrentPassword\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(" for=\"NewPassword\"");

WriteLiteral(">رمز عبور جدید</label>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"NewPassword\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"NewPassword\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(" for=\"ConfirmNewPassword\"");

WriteLiteral(">تکرار رمز عبور جدید</label>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"ConfirmNewPassword\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"ConfirmNewPassword\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n\r\n    <hr />\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Account\ChangePassword.cshtml"
Write(BundleConfig.AddScripts("~/bundles/accountChangePasswordScripts",
        "~/Scripts/jquery.validate.min.js",
        "~/Scripts/jquery.validation-messages.fa.js",
        "~/Scripts/jquery.validation-extensions.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            $('#AccountChangePasswordForm').validate({
                rules: {
                    CurrentPassword: { required: true, minlength: 6, maxlength: 50 },
                    NewPassword: { required: true, minlength: 6, maxlength: 50 },
                    ConfirmNewPassword: { required: true, minlength: 6, maxlength: 50, equalTo: '#NewPassword' }
                }
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
