#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using TES.Common.Enumerations;
    using TES.Common.Extensions;
    using TES.Merchant.Web.UI;
    using TES.Merchant.Web.UI.ViewModels;
    using TES.Security;
    using TES.Web.Core;
    using TES.Web.Core.Extensions;
    using TES.Web.Core.Helper;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Login.cshtml")]
    public partial class _Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<LoginViewModel>
    {
        public _Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Login.cshtml"
  
    ViewBag.Title = "ورود";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-md-4 col-md-offset-4\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" class=\"header-title\"");

WriteLiteral(">ورود</h1>\r\n    </div>\r\n\r\n    <form");

WriteLiteral(" id=\"AccountLoginForm\"");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 237), Tuple.Create("\"", 304)
            
            #line 12 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 246), Tuple.Create<System.Object, System.Int32>(Url.Action("Login", "Account", new { ViewBag.ReturnUrl })
            
            #line default
            #line hidden
, 246), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Account\Login.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(" for=\"Email\"");

WriteLiteral(">نام کاربری</label>\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Email\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" maxlength=\"254\"");

WriteLiteral(" />\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(" for=\"Password\"");

WriteLiteral(">رمز عبور</label>\r\n            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n        </div>\r\n\r\n        <hr />\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-lg btn-block\"");

WriteLiteral(">ورود</button>\r\n        </div>\r\n        \r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1012), Tuple.Create("\"", 1055)
            
            #line 32 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 1019), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "PhoneNumbers")
            
            #line default
            #line hidden
, 1019), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">رمز عبور خود را فراموش کرده اید؟</a>\r\n        </div>\r\n    </form>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Account\Login.cshtml"
Write(BundleConfig.AddScripts("~/bundles/accountLoginScripts",
        "~/Scripts/jquery.validate.js",
        "~/Scripts/jquery.validation-messages.fa.js",
        "~/Scripts/jquery.validation-extensions.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            $('#AccountLoginForm').validate({
                rules: {
                    Email: { required: true, maxlength: 254 },
                    Password: { required: true, minlength: 6, maxlength: 50 }
                }
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
